### PR TITLE
fix and extend NTP servers

### PR DESCRIPTION
**Pull request by cbricart**
(needs to be applied/backported to all branches.. current fix for v2018.2.x branch)

### CODE REVIEW

**Comment by mmalte** [comment]
Firmware with this fix is available:
http://ffac-build.skydisc.net/experimental/

**Comment by cbricart** [comment]
while you surely are absolutely right with your quote about not using the pool directly, I'm not considering us a vendor as it has been intended by the document..
However, this is merely a quick fix anyway to have *any* time sync at all (and most of our devices do need this as they do not have an RTC).
In the mid-term this will change again as there will be Stratum-2 servers, that are part of our own infrastructure. The reason why we have not done that yet is mainly because all of our infra resources are virtual machines which are not that reliable to provide a time source, ymmv

**Comment by jannic** [comment]
I agree with @csamsel that using 2.pool.ntp.org is not ok. And for having "any time sync at all", using `2.openwrt.ntp.org` should be good enough. So I don't think we have a good reason to disregard the rules given by https://www.pool.ntp.org/vendors.html

**Comment by jannic** [comment]
For redundancy, ptbtime2.ptb.de and ptbtime3.ptb.de could be used, as well. Both have IPv6 addresses (ptbtime1 does not).

**Comment by cbricart** [comment]
the PTB servers are (obviously) Stratum-1 servers - so I rather would only use them to »feed« our own Stratum-2 servers mentioned above.
additionally, `ptbtime2.ptb.de` for instance explicitly has its own policy listed here: http://support.ntp.org/bin/view/Servers/PublicTimeServer000216 which basically states »yes we are basically open for anyone using us from Germany/Europe, but please if you do please drop us a note about it«.

So what are your thoughts about `2.de.pool.ntp.org` from the list - is that considered allowed to be used by the vendor policy..? i.e. is `de` yet a vendor ..?

**Comment by csamsel** [comment]
> So what are your thoughts about 2.de.pool.ntp.org from the list - is that considered allowed to be used by the vendor policy..? i.e. is de yet a vendor ..?

No, it's not. The reasoning behind the vendor policy is that vendors can be switched off in case appliances misbehave (by removing the DNS entry).  Obviously switching off germany isnt an option.

**Comment by jannic** [comment]
As the PTB, on their own website, describe how to use their NTP servers, and don't mention any kind of notification, I think it would be fine to use their servers. https://www.ptb.de/cms/ptb/fachabteilungen/abtq/gruppe-q4/ref-q42/zeitsynchronisation-von-rechnern-mit-hilfe-des-network-time-protocol-ntp.html

But, like csamsel, I think that for our use case, just using 2.openwrt.ntp.org would be fine as well. After all, the routers will still work if, for some reason, NTP is not available.

It's great that the NTP pool is offered as a free service. We should honour their rules.

**Comment by cbricart** [comment]
I've quickly added our supernode IPv6 addresses to DNS to have the names ready to be included in `site.conf`.
I've removed both `2.pool.ntp.org` and `2.de.pool.ntp.org` and added our DNS-RR names - left in `2.openwrt.pool.ntp.org` as a distant fallback.

**Pull request merged**
