### PR TITLE
V2023.1.x makefile pr

### PR DESCRIPTION
**Pull request by Djfe**
I merged #93 into v2023.1.x adjusted all files and kept stuff the way it was before, like stuff that v2022.1.x doesn't have (SITEPACKAGES standard for the fallback autoupdater for example).

only the last 5 commits after the merge commit are new.
one of them Fixes a bug that still exists in #93

### CODE REVIEW

**Review by maurerle — APPROVED** [review]
If this builds for all devices, it can be merged

**Comment by Djfe** [comment]
yes, it build everything just fine.

**Comment by Djfe** [comment]
actually I want to test one change later on to drastically  reduce the time that make update-patches takes

**Comment by maurerle** [comment]
I merged these changes through cherrypick and merging v2022.1.x into v2023.1.x
Thank you, for all the work!!

**Pull request closed without merging**
